/**
 * PRD (Product Requirements Document) Output Schema
 *
 * Type-safe schema for RPG-structured PRDs generated by Supervisor agent.
 * Ensures all PRDs follow consistent structure with proper dependency tracking.
 *
 * @module PRDOutputSchema
 * @version 4.1.0
 */

import { z } from 'zod';

/**
 * Phase Enum - Execution phases for features
 */
export const PhaseEnum = z.enum(['1', '2', '3', '4', '5']).transform(Number);

/**
 * Complexity Enum
 */
export const ComplexityEnum = z.enum(['low', 'medium', 'high']);

/**
 * Priority Enum
 */
export const PriorityEnum = z.enum(['low', 'medium', 'high', 'critical']);

/**
 * Feature Schema - Individual feature within a capability
 */
export const FeatureSchema = z.object({
  name: z.string().min(1, 'Feature name is required'),
  description: z.string().min(10, 'Feature description must be at least 10 characters'),
  dependsOn: z.array(z.string()).describe('Array of feature names this depends on'),
  phase: z.number().min(1).max(5).describe('Execution phase (1-5)'),
  complexity: ComplexityEnum,
  estimatedHours: z.number().min(0).describe('Estimated hours to complete'),
  acceptanceCriteria: z.array(z.string()).min(1, 'At least one acceptance criterion required'),
  technicalNotes: z.array(z.string()).optional().describe('Technical implementation notes'),
});

export type Feature = z.infer<typeof FeatureSchema>;

/**
 * Capability Schema - RPG-structured capability containing multiple features
 */
export const CapabilitySchema = z.object({
  capability: z.string().min(1, 'Capability name is required'),
  description: z.string().optional().describe('Capability description'),
  features: z.array(FeatureSchema).min(1, 'At least one feature required per capability'),
  phase: z.number().min(1).max(5).describe('Overall phase for this capability'),
});

export type Capability = z.infer<typeof CapabilitySchema>;

/**
 * Non-Functional Requirements Schema
 */
export const NonFunctionalRequirementsSchema = z.object({
  performance: z.array(z.string()).describe('Performance requirements (e.g., <100ms API response)'),
  security: z.array(z.string()).describe('Security requirements (e.g., Argon2id password hashing)'),
  scalability: z.array(z.string()).describe('Scalability requirements (e.g., 10k concurrent users)'),
  reliability: z.array(z.string()).optional().describe('Reliability/uptime requirements'),
  usability: z.array(z.string()).optional().describe('Usability requirements'),
  compliance: z.array(z.string()).optional().describe('Compliance requirements (GDPR, HIPAA, etc.)'),
});

export type NonFunctionalRequirements = z.infer<typeof NonFunctionalRequirementsSchema>;

/**
 * Technology Stack Schema
 */
export const TechnologyStackSchema = z.object({
  backend: z.object({
    runtime: z.string().default('Node.js 20 LTS'),
    language: z.string().default('TypeScript 5.3+'),
    framework: z.string().describe('Backend framework (Fastify, NestJS, etc.)'),
    database: z.string().describe('Database (PostgreSQL 16+, etc.)'),
    authentication: z.string().optional().describe('Auth strategy (JWT, OAuth2, etc.)'),
  }).optional(),
  frontend: z.object({
    framework: z.string().default('Next.js 15+'),
    react: z.string().default('React 19+'),
    styling: z.string().default('TailwindCSS 4+ + shadcn/ui'),
    stateManagement: z.string().optional().describe('State management (Zustand, Redux, etc.)'),
  }).optional(),
  infrastructure: z.object({
    containerization: z.string().default('Docker 25+'),
    orchestration: z.string().optional().describe('Kubernetes, Docker Compose, etc.'),
    cicd: z.string().default('GitHub Actions'),
    monitoring: z.array(z.string()).optional().describe('Monitoring tools (Prometheus, Grafana, etc.)'),
  }).optional(),
});

export type TechnologyStack = z.infer<typeof TechnologyStackSchema>;

/**
 * PRD Schema - Complete Product Requirements Document
 */
export const PRDSchema = z.object({
  // Metadata
  projectName: z.string().min(1, 'Project name is required'),
  version: z.string().default('1.0.0'),
  createdAt: z.string().datetime().default(() => new Date().toISOString()),
  stakeholder: z.string().min(1, 'Stakeholder name/email is required'),

  // Business context
  businessGoals: z.array(z.string()).min(1, 'At least one business goal required'),
  targetAudience: z.array(z.string()).optional().describe('Target user personas'),
  successMetrics: z.array(z.string()).optional().describe('KPIs and success metrics'),

  // Technical requirements
  technicalRequirements: z.array(z.string()).min(1, 'At least one technical requirement required'),
  technologyStack: TechnologyStackSchema.optional(),

  // RPG-structured functional requirements
  functionalRequirements: z.array(CapabilitySchema).min(1, 'At least one capability required'),

  // Non-functional requirements
  nonFunctionalRequirements: NonFunctionalRequirementsSchema,

  // Constraints and assumptions
  constraints: z.array(z.string()).optional().describe('Project constraints (budget, time, etc.)'),
  assumptions: z.array(z.string()).optional().describe('Key assumptions made'),
  risks: z.array(z.object({
    risk: z.string(),
    severity: z.enum(['low', 'medium', 'high', 'critical']),
    mitigation: z.string(),
  })).optional(),

  // Timeline
  timeline: z.object({
    startDate: z.string().datetime().optional(),
    targetLaunchDate: z.string().datetime().optional(),
    phases: z.array(z.object({
      phase: z.number().min(1).max(5),
      name: z.string(),
      duration: z.string().describe('Duration (e.g., "2 weeks", "1 month")'),
      deliverables: z.array(z.string()),
    })).optional(),
  }).optional(),

  // Quality standards
  qualityStandards: z.object({
    testCoverage: z.number().min(0).max(100).default(90),
    performanceTargets: z.array(z.string()).optional(),
    securityStandards: z.array(z.string()).default(['OWASP Top 10 2025', 'NIST SSDF']),
  }).optional(),
});

export type PRD = z.infer<typeof PRDSchema>;

/**
 * Helper function to validate PRD structure
 */
export function validatePRD(prd: unknown): { success: boolean; data?: PRD; errors?: z.ZodError } {
  const result = PRDSchema.safeParse(prd);

  if (result.success) {
    return { success: true, data: result.data };
  } else {
    return { success: false, errors: result.error };
  }
}

/**
 * Helper function to extract all features from PRD in dependency order
 */
export function extractFeaturesInOrder(prd: PRD): Feature[] {
  const allFeatures: Feature[] = [];

  // Sort capabilities by phase first
  const sortedCapabilities = [...prd.functionalRequirements].sort((a, b) => a.phase - b.phase);

  sortedCapabilities.forEach((capability) => {
    // Add all features from this capability
    allFeatures.push(...capability.features);
  });

  return allFeatures;
}

/**
 * Helper function to calculate total estimated hours
 */
export function calculateTotalHours(prd: PRD): number {
  return prd.functionalRequirements.reduce((total, capability) => {
    return total + capability.features.reduce((capTotal, feature) => {
      return capTotal + feature.estimatedHours;
    }, 0);
  }, 0);
}

/**
 * Helper function to get features by phase
 */
export function getFeaturesByPhase(prd: PRD, phase: number): Feature[] {
  return prd.functionalRequirements
    .filter((cap) => cap.phase === phase)
    .flatMap((cap) => cap.features.filter((feat) => feat.phase === phase));
}
